[package]
name = "typstgen"
version = "0.6.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
color-print = "0.3.7"
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
whoami = "2.1.0"
